#!/bin/bash

#TO DO:
#Create a menu that separates actions
#1. copy custom files/folders -> a) choose b) all in list
#2. add/modify repos and run update -> a) choose b) all in list
#3. download specific programs not in synaptic -> a) choose b) all in list
#4. install programs -> a) choose b) all in list
#5. do everything
echo "this script requires the internet, wpstart.sh, and all your home custom settings such as your .ssh folder (in the same directory as this script)"
sleep 2
echo " Welcome to tRiskItE's Ubuntu installall script.
1 - Copy configuration files, boot scripts, ssh keys, etc
2 - add custom repos & update sources
3 - download non apt installation files
4 - install all programs & start synergyc
5 - do everything
q - quit
Please select a task: "
read i

if [ $i = "q" ]
then
exit
fi

if [ $i -eq 1 -o $i -eq 5 ]
then
#<copy custom files to new installation & enable init.d autoload
  sudo cp wpstart.sh /etc/init.d/
  sudo update-rc.d wpstart.sh defaults
  mkdir ~/.ssh
  sudo cp -R .ssh/* ~/.ssh/
  sudo mv ~/.bashrc ~/.bashrc_bak_wps
  sudo cp .bashrc ~/
  #sudo mkdir ~/.compiz-1
  mkdir ~/.config
  mkdir ~/.config/autostart
  sudo cp -R .config/autostart/* ~/.config/autostart/
  mkdir ~/.gconf
  sudo cp -R .gconf/* ~/.gconf/
  #sudo mkdir ~/.gconfd
  #sudo mkdir ~/.gnome2
#copy custom files to new installation & enable init.d autoload>
fi

if [ $i -eq 2 -o $i -eq 5 ]
then
#<add repos and update
  #<dropbox
    sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 5044912E
    echo "deb http://linux.dropbox.com/ubuntu $(lsb_release -cs) main" | sudo tee "/etc/apt/sources.list.d/dropbox.list" > /dev/null
  #dropbox>
  #<replicator
    sudo add-apt-repository "deb http://archive.canonical.com/ubuntu precise partner"
    sudo apt-add-repository ppa:flexiondotorg/java
  #replicator>
  sudo apt-get update
#add repos and update>
fi
if [ $i -eq 3 -o $i -eq 5 ]
then
#<download packages not supported by synaptic
  sudo wget http://prdownloads.sourceforge.net/aoi/ArtOfIllusion291-Linux.zip && unzip ArtOfIllusion291-Linux.zip 
  sudo wget http://replicatorg.googlecode.com/files/replicatorg-0034-linux.tgz && tar -xvzf replicatorg-0034-linux.tgz
  wget http://www.teamviewer.com/download/teamviewer_linux_x64.deb #install teamviewer
#download packages not supported by synaptic>
fi
if [ $i -eq 4 -o $i -eq 5 ]
then
#<install everything
  sudo apt-get install --assume-yes -y ssh lmbench python-gpgme chromium-browser python-software-properties ubuntu-restricted-extras synergy build-essential bison curl git-core git-gui git-doc gcc g++ linux-headers-generic openjdk-6-jre vim-gnome gnome-do compizconfig-backend-gconf compiz-fusion-plugins-main compiz-plugins blender compiz-plugins-main hardinfo python python-tk unzip
  sudo dpkg -i teamviewer_linux_x64.deb #install teamviewer
  sudo apt-get -y --force-yes install nautilus-dropbox #install dropbox
  sudo apt-get -f --assume-yes install
  dropbox start -i #install dropbox
  #<install 3d printing software AOI
    unzip ArtOfIllusion291-Linux.zip 
    cd ArtOfIllusion
    sudo ./aoisetup
  #install 3d printing software AOI>
  #<install special components for replicatorG
    sudo apt-get install --assume-y -y sun-java6-jre sun-java6-plugin
    sudo update-alternatives --config java
    echo "select /usr/lib/jvm/java-6-sun/jre/bin/java"
  #install special components for replicatorG>
#install everything>
#<start programs
  synergyc --name box 192.168.1.118:24800 &
#start programs>
fi


##NOTES ONLY##
##3d printing CAUSES ERRORS: python-psyco
#sudo add-apt-repository "deb http://archive.canonical.com/ubuntu natty partner"
#chromium beta
#sudo add-apt-repository ppa:chromium-daily/beta && sudo apt-get update && sudo apt-get install --assume-yes chromium-browser
#this would have been useful: http://howto.blbosti.com/2010/02/simple-ubuntu-install-script/http://howto.blbosti.com/2010/02/simple-ubuntu-install-script/
#sudo apt-get install -y 
#ssh python ruby rails gems rvm text editor - > vim w/ settings display preferences hardware / battery preferences bluetooth audio/visual/media graphics editors - blender 3d design - etc
#To get a list of packages installed locally and save as a text file called packages on your desktop do this in your terminal:
#sudo dpkg --get-selections > ~/Desktop/packages
##Then, when installing to the new computer
#sudo dpkg --set-selections < ~/Desktop/packages && sudo apt-get -u dselect-upgrade

#Step 1: Store the list of installed packages
#Run the following command on the source machine to store the installed packages names in ~/pkglist:
#sudo dpkg --get-selections | sed "s/.*deinstall//" | sed "s/install$//g" > ~/pkglist

#Step 2: Transfer your config
#Use scp or rsync or even a flash drive to transfer your home directory (~/*, ~/.*), the source list (/etc/apt/sources.list) and any other files you customized or installed (like apache config under /etc or softwares on /opt) from the source machine to the target one.

#Step 3: Install packages
#On the target machine run the following command in a failsafe terminal session to install your packages:

#sudo aptitude update && cat pkglist | xargs sudo aptitude install -y
